config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get "/dashboard", to: "users#dashboard", as: "dashboard"
    get "/my_page", to: "users#show", as: "my_page"
    get '/confirm', to: "users#confirm", as: "confirm"
    patch '/deactivate', to: "users#deactivate", as: "deactivate"
    resource :users, only: [:edit, :update]
    post '/my_task_refinement', to: "users#my_task_refinement", as: "my_task_refinement"
    post '/my_project_refinement', to: "users#my_project_refinement", as: "my_project_refinement"

    resources :projects, only: [:show, :new, :create, :edit, :update, :destroy] do
      get '/gantt_chart', to: "projects#gantt_chart", as: "gantt_chart"
      get '/parent_tasks/bulk_new', to: "parent_tasks#bulk_new", as: "parent_task_bulk_new"
      post '/parent_tasks/bulk_create', to: "parent_tasks#bulk_create", as: "parent_task_bulk_create"
      get '/parent_tasks/bulk_edit', to: "parent_tasks#bulk_edit", as: "parent_task_bulk_edit"
      patch '/parent_tasks/bulk_update', to: "parent_tasks#bulk_update", as: "parent_task_bulk_update"
      get '/parent_tasks/bulk_delete', to: "parent_tasks#bulk_delete", as: "parent_task_bulk_delete"
      delete '/parent_tasks/bulk_destroy', to: "parent_tasks#bulk_destroy", as: "parent_task_bulk_destroy"
      resources :parent_tasks, only: [:show, :new, :create, :edit, :update, :destroy]
      patch '/child_tasks/:id/select_update', to: "child_tasks#select_update", as: "child_task_select_update"
      get '/child_tasks/bulk_new', to: "child_tasks#bulk_new", as: "child_task_bulk_new"
      post '/child_tasks/bulk_create', to: "child_tasks#bulk_create", as: "child_task_bulk_create"
      get '/child_tasks/bulk_edit', to: "child_tasks#bulk_edit", as: "child_task_bulk_edit"
      patch '/child_tasks/bulk_update', to: "child_tasks#bulk_update", as: "child_task_bulk_update"
      get '/child_tasks/bulk_delete', to: "child_tasks#bulk_delete", as: "child_task_bulk_delete"
      delete '/child_tasks/bulk_destroy', to: "child_tasks#bulk_destroy", as: "child_task_bulk_destroy"
      resources :child_tasks, only: [:show, :new, :create, :edit, :update, :destroy]
      resources :project_members, only: [:show, :new, :create, :edit, :update, :destroy]
      resources :documents, only: [:show, :new, :create, :edit, :update, :destroy]
    end
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: "users_guest_sign_in"
  end

  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  has_many :project_members
  has_many :child_tasks
  has_many :documents

  has_one_attached :profile_image

  validates :display_name, presence: true
  validates :user_name, presence: true, uniqueness: true, format: { with: /\A[a-z0-9-]+\z/, message: "は半角英数字で入力してください。" }
  validates :email, presence: true, uniqueness: true
  validates :is_deleted, inclusion: [true, false]

  def self.have_editor_authority(project_id, user_id)
    ProjectMember.permissions[ProjectMember.find_by(project_id: project_id, user_id: user_id).permission] >= 10
  end

  def self.have_administrator_authority(project_id, user_id)
    ProjectMember.permissions[ProjectMember.find_by(project_id: project_id, user_id: user_id).permission] >= 20
  end

  def check_deleted
    if self.is_deleted
      "無効"
    else
      "有効"
    end
  end

  def self.select_deleted
    select_deleted = [['有効', false], ['無効', true]]
  end

  def task_count
    self.child_tasks.count
  end

  def task_complete
    self.child_tasks.where(progress: 100).count
  end

  def task_remaining
    task_count - task_complete
  end

  def task_progress
    sum_progress = self.child_tasks.sum(:progress)
    count_tasks = self.child_tasks.count
    if count_tasks == 0
      0
    elsif sum_progress == 0
      0
    else
      (sum_progress/count_tasks).floor
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(user_name: 'guestuser') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.display_name = "ゲストユーザー"
      user.email = "guest@example.com"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
      flash[:notice] = "プロフィールの更新に成功しました。"
    else
      flash.now[:alert] = "プロフィールの更新に失敗しました。"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:display_name, :user_name, :email, :is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="wrapper">
  <div class="container">
    <div class="form-container">
      <div class="box-100">
        <h2><%= @user.display_name %>さんの編集</h2>
      </div>

      <%= render "layouts/errors", obj: @user %>

      <div class="box-100">
        <%= form_with model: @user, url: admin_user_path(@user.id), local: true, method: :patch do |f| %>
          <div class="form-field">
            <%= f.label :display_name, "表示名" %><br />
            <%= f.text_field :display_name, autofocus: true, autocomplete: "display_name", class: "form-textbox" %>
          </div>

          <div class="form-field">
            <%= f.label :user_name, "ユーザーネーム" %><br />
            <%= f.text_field :user_name, autofocus: true, autocomplete: "user_name", class: "form-textbox" %>
          </div>

          <div class="form-field">
            <%= f.label :email, "メールアドレス" %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-textbox" %>
          </div>

          <div class="form-field">
              <%= f.label :is_deleted, "ステータス" %><br>
              <%= f.select :is_deleted, options_for_select(User.select_deleted, @user.is_deleted),{ }, {id: "", class: "form-textbox"} %>
          </div>

          <div class="form-action">
            <%= f.submit "更新", class: "btn green-color" %>
          </div>
        <% end %>

        <div class="form-action">
          <%= link_to "戻る", admin_users_path, method: :get, class: "btn blue-color" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="wrapper">
  <div class="container flex-box">
    <div class="box-100">
      <h2>ユーザー一覧</h2>
    </div>

    <div class="box-100">
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>表示名</th>
            <th>ユーザーネーム</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.display_name %></td>
            <td><%= link_to user.user_name, admin_user_path(user.id), method: :get %></td>
            <td><%= user.email %></td>
            <td><%= user.check_deleted %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="form-container">
      <div class="box-100">
        <h2><%= @user.display_name %>さんの詳細</h2>
      </div>

      <div class="box-100">
        <div class="form-field">
          <p>表示名<br>
          <span class="display-textbox"><%= @user.display_name %></span></p>
        </div>

        <div class="form-field">
          <p>ユーザーネーム<br>
          <span class="display-textbox"><%= @user.user_name %></span></p>
        </div>

        <div class="form-field">
          <p>メールアドレス<br>
          <span class="display-textbox"><%= @user.email %></p>
        </div>

        <div class="form-field">
          <p>ステータス<br>
          <span class="display-textbox"><%= @user.check_deleted %></p>
        </div>

        <div class="form-action">
          <%= link_to "編集", edit_admin_user_path(@user.id), method: :get, class: "btn green-color" %>
        </div>

        <div class="form-action">
          <%= link_to "戻る", admin_users_path, method: :get, class: "btn blue-color" %>
        </div>
      </div>
    </div>
  </div>
</div>