config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get "/dashboard", to: "users#dashboard", as: "dashboard"
    get "/my_page", to: "users#show", as: "my_page"
    get '/confirm', to: "users#confirm", as: "confirm"
    patch '/deactivate', to: "users#deactivate", as: "deactivate"
    resource :users, only: [:edit, :update]
    post '/my_task_refinement', to: "users#my_task_refinement", as: "my_task_refinement"
    post '/my_project_refinement', to: "users#my_project_refinement", as: "my_project_refinement"

    resources :projects, only: [:show, :new, :create, :edit, :update, :destroy] do
      get '/gantt_chart', to: "projects#gantt_chart", as: "gantt_chart"
      get '/parent_tasks/bulk_new', to: "parent_tasks#bulk_new", as: "parent_task_bulk_new"
      post '/parent_tasks/bulk_create', to: "parent_tasks#bulk_create", as: "parent_task_bulk_create"
      get '/parent_tasks/bulk_edit', to: "parent_tasks#bulk_edit", as: "parent_task_bulk_edit"
      patch '/parent_tasks/bulk_update', to: "parent_tasks#bulk_update", as: "parent_task_bulk_update"
      get '/parent_tasks/bulk_delete', to: "parent_tasks#bulk_delete", as: "parent_task_bulk_delete"
      delete '/parent_tasks/bulk_destroy', to: "parent_tasks#bulk_destroy", as: "parent_task_bulk_destroy"
      resources :parent_tasks, only: [:show, :new, :create, :edit, :update, :destroy]
      patch '/child_tasks/:id/select_update', to: "child_tasks#select_update", as: "child_task_select_update"
      get '/child_tasks/bulk_new', to: "child_tasks#bulk_new", as: "child_task_bulk_new"
      post '/child_tasks/bulk_create', to: "child_tasks#bulk_create", as: "child_task_bulk_create"
      get '/child_tasks/bulk_edit', to: "child_tasks#bulk_edit", as: "child_task_bulk_edit"
      patch '/child_tasks/bulk_update', to: "child_tasks#bulk_update", as: "child_task_bulk_update"
      get '/child_tasks/bulk_delete', to: "child_tasks#bulk_delete", as: "child_task_bulk_delete"
      delete '/child_tasks/bulk_destroy', to: "child_tasks#bulk_destroy", as: "child_task_bulk_destroy"
      resources :child_tasks, only: [:show, :new, :create, :edit, :update, :destroy]
      resources :project_members, only: [:show, :new, :create, :edit, :update, :destroy]
      resources :documents, only: [:show, :new, :create, :edit, :update, :destroy]
    end
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: "users_guest_sign_in"
  end

  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
  end

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="box-100 errors-text">
    <h3><%= obj.errors.count %> 件のエラーが発生しました</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer-wrapper">
  <div class="footer-container footer-text">
  	<p>©SelfManagementApp</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header-wrapper">
  <div class="header-container header-flex-box">
    <div class="header-left">
      <% if user_signed_in? %>
        <h1 class="header-logo"><%= link_to "SelfManagementApp", dashboard_path, method: :get %></h1>
      <% elsif admin_signed_in? %>
        <h1 class="header-logo"><%= link_to "SelfManagementApp", admin_root_path, method: :get %></h1>
      <% else %>
        <h1 class="header-logo"><%= link_to "SelfManagementApp", root_path, method: :get %></h1>
      <% end %>
    </div>

    <div class="header-right">
      <nav>
        <ul class="nav-list">
          <% if admin_signed_in? %>
            <li class="nav-list-item"><i class="fa fa-file-lines"></i><%= link_to "ダッシュボード", admin_root_path, method: :get %></li>
            <li class="nav-list-item"><i class="fa fa-user"></i><%= link_to "ユーザー一覧", admin_users_path, method: :get %></li>
            <li class="nav-list-item"><i class="fa fa-right-from-bracket"></i><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
          <% elsif user_signed_in? %>
            <li class="nav-list-item"><i class="fa fa-file-lines"></i><%= link_to "ダッシュボード", dashboard_path, method: :get %></li>
            <li class="nav-list-item"><i class="fa fa-user-gear"></i><%= link_to "マイページ", my_page_path, method: :get %></li>
            <li class="nav-list-item"><i class="fa fa-right-from-bracket"></i><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li class="nav-list-item"><i class="fa fa-user-plus"></i><%= link_to "新規登録", new_user_registration_path, method: :get %></li>
            <li class="nav-list-item"><i class="fa fa-right-to-bracket"></i><%= link_to "ログイン", new_user_session_path, method: :get %></li>
          <% end %>
        </ul>
      </nav>
    </div>

  </div>
</header>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
  <div class="wrapper green-color">
    <div class="notice-container notice-text">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="wrapper red-color">
    <div class="notice-container notice-text">
      <%= flash[:alert] %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SelfManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--CDN-->
    <script src="https://kit.fontawesome.com/06744c5d82.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css" />
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js" integrity="sha256-6XMVI0zB8cRzfZjqKcD01PBsAy3FlDASrlC8SxCpInY=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/frappe-gantt/0.5.0/frappe-gantt.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/frappe-gantt/0.5.0/frappe-gantt.min.js"></script>

    <!--ファイル管理-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-XQ3H7G6Q8P"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-XQ3H7G6Q8P');
    </script>

  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/notice" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>